openapi: 3.0.0
info:
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: Movie2gether
  termsOfService: 'http://swagger.io/terms/'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/alex0acw/oocl-tatp/1.0.0
  - url: 'https://petstore.swagger.io/v2'
tags:
  - name: Movie
    description: Movie details.
  - name: User
    description: User information.
  - name: Booking
    description: Booking and Payment API.
  - name: Session
    description: Movie session detail.
  - name: Static
    description: Static files.
paths:
  /movie:
    get:
      tags:
        - "Movie"
      parameters:
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: sortBy
          schema:
            type: string
            enum: ['recommanded', 'top']
            default: 'recommanded'
        - in: query
          name: sortOrder
          schema:
            type: string
            enum: [asc, desc]
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
  /movie/{id}/comments:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      parameters:
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
        - in: query
          name: page
          required: true
          schema:
            type: integer
      tags:
        - "Movie"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    author:
                      type: string
                    content:
                      type: string
                    rating:
                      type: integer
  /session:
    get:
      description: 'Query for movie sessions'
      parameters:
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: movieId
          schema:
            type: string
        - in: query
          name: cinemaId
          schema:
            type: string
      tags:
        - "Session"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionOverview'
  /session/{id}:
    get:
      description: 'Movie session details'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      tags:
        - "Session"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionDetail'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        preference:
          type: array
          items:
            type: string
        friends:
          type: array
          items:
            $ref: '#/components/schemas/User'
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/Booking'
    Movie:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: array
          items:
            type: string
        rating:
          type: number
        posterUri:
          type: string
        description:
          type: string
    Comment:
      type: object
      properties:
        id:
          type: string
        author:
          type: string
        content:
          type: string
        rating:
          type: integer
    Booking:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        sessionId:
          type: string
        seatId:
          type: string
    SessionOverview:
      type: object
      properties:
        id:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        movieId:
          type: string
        movieName:
          type: string
        cinemaId:
          type: string
        cinemaName:
          type: string
        theaterId:
          type: string
        theaterName:
          type: string
        totalSeats:
          type: integer
        avilableSeats:
          type: integer
    SessionDetail:
      type: object
      properties:
        id:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        movie:
          $ref: '#/components/schemas/Movie'
        cinema:
          $ref: '#/components/schemas/Cinema'
        theater:
          $ref: '#/components/schemas/Theater'
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/Booking'
    Cinema:
      type: object
      properties:
        id:
          type: string
        address:
          type: string
        name:
          type: string
        theaters:
          type: array
          items:
            $ref: '#/components/schemas/Theater'
    Theater:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        seats:
          type: array
          items:
            $ref: '#/components/schemas/Seat'
    Seat:
      type: object
      description: "Represent one seat in the theater"
      properties:
        number:
          type: string
          description: 'Seat number, e.g. "G11" to identify seat inside a cinema'
        x:
          type: number
          description: "lateral distance from screen"
        y:
          type: number
          description: "perpendicular distance from screen"
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: Details for new user registration
      required: true