spring:
  data:
    mongodb:
      uri : ${MONGO_DB_PATH}
management:
  endpoint:
    health:
      show-components: 'always'

# App Properties
  bezkoder.app.jwtSecret= bezKoderSecretKey
  bezkoder.app.jwtExpirationMs= 86400000